In [1]:
import pandas as pd

path to csv file.....

In [2]:
path_csv = "/kaggle/input/sarcastic-comments-on-reddit/train-balanced-sarcasm.csv"

Load the CSV File

In [3]:
df = pd.read_csv(path_csv)


Lets shuffle and see the top 20 rows,,

In [4]:
df_shuffled = df.sample(frac=1).reset_index(drop=True)
df_shuffled.head(20)

label                                            comment  \
0       1               We definitely need more passiveness.   
1       0  I'm thinking it happened when they were forced...   
2       0                                        I hurt him.   
3       1  Yeah and the always picked Azir/Viktor in the ...   
4       1  But dae MRAs are the "rational" ones and ass j...   
5       1          Freaking broke people get all the breaks.   
6       1  You know he consulted with himself and is lead...   
7       1  BJ Penn paid him that much and Dolce didnt do ...   
8       0  I've said multiple times that I could stay san...   
9       1         But but... lane splitting is the safest...   
10      0                                              10/10   
11      0  lmao it started at apple store.... because it'...   
12      1  They are going to make a profit with vehicle b...   
13      0            hasn't Chicago suffered enough already?   
14      1  He's a man though so women are allowed to hit ...   
15      0                       And the Monster Energy logo.   
16      1  I've never, ever, ever, seen a 2.0 shipping de...   
17      1                       Wow would never have guessed   
18      0                                                Yes   
19      1             Oh that is just what the USA needs now   

                 author            subreddit  score  ups  downs     date  \
0             Xensphere      leagueoflegends      1    1      0  2012-10   
1            cjandstuff            cablefail      1    1      0  2016-04   
2           ThatOneFace  raisedbynarcissists      2    2      0  2015-05   
3             KeeganKGB      leagueoflegends      2    2      0  2015-07   
4          FattyMcPatty    againstmensrights     24   24      0  2015-07   
5          the_sam_ryan      personalfinance      2    2      0  2015-02   
6           tomanonimos          nottheonion      0    0      0  2016-03   
7      thearsonistsaint                  MMA      2    2      0  2015-07   
8   Puritan_Sensibility            AskReddit      2   -1     -1  2016-10   
9    highspeed_lowdrag2          JusticePorn      0    0      0  2015-02   
10        TheKinkMaster          forearmporn      4    4      0  2015-07   
11        JonasBrosSuck         KimmySchmidt      9    9      0  2016-04   
12             d2_ricci                  Amd     23   23      0  2016-04   
13         schmeebasaur                  MLS      1   -1     -1  2016-10   
14       Texas_sniper41               videos    122  122      0  2015-10   
15   DeathWalkingTerror                 cars      1    1      0  2015-01   
16              ranhalt              soylent      1   -1     -1  2016-11   
17        YayScience120           psychology      1    1      0  2016-09   
18              Leafs17              xboxone      1    1      0  2016-09   
19   monkeybonerinmouth             politics      2   -1     -1  2016-11   

            created_utc                                     parent_comment  
0   2012-10-20 07:50:23  I was actually happy with the new turret attac...  
1   2016-04-12 16:31:27  Walked into a site to do some installs and see...  
2   2015-05-30 12:59:55  Losing someone does not make you a bad person....  
3   2015-07-11 22:40:18  Why TSM (or any NA team) will have NO chance a...  
4   2015-07-18 20:30:22  In a post titled "#ShootAFeministInTheFace", J...  
5   2015-02-02 18:05:36  Yeah being short on money things like snacks a...  
6   2016-03-16 21:12:20          Trump: I consult myself on foreign policy  
7   2015-07-07 01:03:12  Hmm I'm not sure about Ronda, she uses Mike Do...  
8   2016-10-26 17:09:56  I don't do that specifically, but I'm definite...  
9   2015-02-20 20:32:56  Motorcyclist receives justice for driving reck...  
10  2015-07-22 09:03:59           So I didn't know this sub was a thing...  
11  2016-04-16 19:26:01  Episode Discussion: S02E04 "Kimmy Kidnaps Gret...  
12  2016-04-14 02:24:27  I don't know what they are gonna do,

Lets filter the csv and drop the unwarranted columns and retain only the sarcastic labels..

In [5]:
df_filtered = df[df['label'] == 1]
df_filtered.head(10)

label                                            comment          author  \
33       1                But they'll have all those reviews!   RoguishPoppet   
44       1  wow it is totally unreasonable to assume that ...        pb2crazy   
45       1  Ho ho ho... But Melania said that there is no ...        pb2crazy   
66       1  I can't wait until @potus starts a twitter war...       kitduncan   
69       1  gotta love the teachers who give exams on the ...           DEP61   
74       1           Hoiberg said "great players", not Dwight        deezee72   
76       1  Oh, I never realized it was so easy, why had I...   SatanicBeaver   
160      1                     Exactly, no reason whatsoever.         Bifi323   
169      1  Hank would have a great time in the Legends of...       CIearMind   
193      1  I remember reading all of those stories in the...  MiggidyMacDewi   

           subreddit  score  ups  downs     date          created_utc  \
33    ProductTesting      0   -1     -1  2016-11  2016-11-01 02:04:59   
44          politics      2   -1     -1  2016-11  2016-11-01 02:42:11   
45          politics      8   -1     -1  2016-10  2016-10-18 16:20:53   
66          politics      3   -1     -1  2016-11  2016-11-01 03:22:33   
69       CFBOffTopic      3   -1     -1  2016-11  2016-11-01 03:30:11   
74               nba     29   -1     -1  2016-11  2016-11-01 03:45:25   
76         AskReddit      1   -1     -1  2016-11  2016-11-01 03:51:16   
160  oddlysatisfying      1   -1     -1  2016-11  2016-11-01 09:59:54   
169      supergirlTV      3   -1     -1  2016-11  2016-11-01 10:23:55   
193           videos      1   -1     -1  2016-11  2016-11-01 12:03:56   

                                        parent_comment  
33   The dumb thing is, they are risking their sell...  
44   Clinton campaign accuses FBI of 'blatant doubl...  
45   Anyone else think that it was interesting the ...  
66   Here's what happens when Obama gives up his Tw...  
69   Monday night Drinking thread Brought to You by...  
74                              except the 2012 lakers  
76   A little self lovin can turn that 99 into a 10...  
160         To make predators think they're poisonous?  
169  Pretty inconvenient if they landed anywhere pr...  
193  You as everyone else are MISSING THE ENTIRE PO...

In [6]:
texts = df_filtered['comment'].tolist()


In [7]:
type(texts)

list

In [8]:
df_filtered.to_csv('sample1.txt', sep='\t', index=False, header=False)

In [9]:
with open('sample.txt', 'w') as f:
    # Write each item in the list to a new line in the file
    for item in texts:
        f.write("%s\n" % item)

In [10]:
txt_path = "/kaggle/working/sample.txt"

In [11]:
with open(txt_path, 'r',encoding='utf-8') as f:
    text = f.read()

In [12]:
print("length of the dataset in characters: ", len(text))

length of the dataset in characters:  29033476


In [13]:
print(text[:1000])

But they'll have all those reviews!
wow it is totally unreasonable to assume that the agency that covered up Bush war crimes because "muh republican party" would be partisan as fuck
Ho ho ho... But Melania said that there is no way it could have happened because she didn't know the woman!
I can't wait until @potus starts a twitter war against Morning Joe.
gotta love the teachers who give exams on the day after halloween
Hoiberg said "great players", not Dwight
Oh, I never realized it was so easy, why had I, and every other lonely person on earth never thought of that before?
Exactly, no reason whatsoever.
Hank would have a great time in the Legends of Tomorrow.
I remember reading all of those stories in the news about riot police marching into the Volvo head offices with truncheons and beating the designers until they invented the seatbelt.
can't watch it and get into heaven son, that's stealing :(
Yeah, those kids who can't eat peanuts without dying or milk without diarrhea, or the ra

In [14]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !"#$%&'()*+,-./0123456789:;=?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
95


In [15]:


# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))



[72, 73, 73, 2, 84, 72, 69, 82, 69]
hii there


In [16]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([29033476]) torch.int64
tensor([34, 85, 84,  2, 84, 72, 69, 89,  9, 76, 76,  2, 72, 65, 86, 69,  2, 65,
        76, 76,  2, 84, 72, 79, 83, 69,  2, 82, 69, 86, 73, 69, 87, 83,  3,  1,
        87, 79, 87,  2, 73, 84,  2, 73, 83,  2, 84, 79, 84, 65, 76, 76, 89,  2,
        85, 78, 82, 69, 65, 83, 79, 78, 65, 66, 76, 69,  2, 84, 79,  2, 65, 83,
        83, 85, 77, 69,  2, 84, 72, 65, 84,  2, 84, 72, 69,  2, 65, 71, 69, 78,
        67, 89,  2, 84, 72, 65, 84,  2, 67, 79, 86, 69, 82, 69, 68,  2, 85, 80,
         2, 34, 85, 83, 72,  2, 87, 65, 82,  2, 67, 82, 73, 77, 69, 83,  2, 66,
        69, 67, 65, 85, 83, 69,  2,  4, 77, 85, 72,  2, 82, 69, 80, 85, 66, 76,
        73, 67, 65, 78,  2, 80, 65, 82, 84, 89,  4,  2, 87, 79, 85, 76, 68,  2,
        66, 69,  2, 80, 65, 82, 84, 73, 83, 65, 78,  2, 65, 83,  2, 70, 85, 67,
        75,  1, 40, 79,  2, 72, 79,  2, 72, 79, 16, 16, 16,  2, 34, 85, 84,  2,
        45, 69, 76, 65, 78, 73, 65,  2, 83, 65, 73, 68,  2, 84, 72, 65, 84,  2,
     

In [17]:
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [18]:


block_size = 8
train_data[:block_size+1]



tensor([34, 85, 84,  2, 84, 72, 69, 89,  9])

In [19]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([34]) the target: 85
when input is tensor([34, 85]) the target: 84
when input is tensor([34, 85, 84]) the target: 2
when input is tensor([34, 85, 84,  2]) the target: 84
when input is tensor([34, 85, 84,  2, 84]) the target: 72
when input is tensor([34, 85, 84,  2, 84, 72]) the target: 69
when input is tensor([34, 85, 84,  2, 84, 72, 69]) the target: 89
when input is tensor([34, 85, 84,  2, 84, 72, 69, 89]) the target: 9


In [20]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[76, 69,  2, 66, 73, 84, 67, 72],
        [78, 79, 84,  2, 68, 85, 77, 66],
        [78, 68,  2, 71, 69, 84, 65, 87],
        [69,  2, 87, 72, 79,  2, 79, 66]])
targets:
torch.Size([4, 8])
tensor([[69,  2, 66, 73, 84, 67, 72,  2],
        [79, 84,  2, 68, 85, 77, 66, 16],
        [68,  2, 71, 69, 84, 65, 87, 65],
        [ 2, 87, 72, 79,  2, 79, 66, 86]])
----
when input is [76] the target: 69
when input is [76, 69] the target: 2
when input is [76, 69, 2] the target: 66
when input is [76, 69, 2, 66] the target: 73
when input is [76, 69, 2, 66, 73] the target: 84
when input is [76, 69, 2, 66, 73, 84] the target: 67
when input is [76, 69, 2, 66, 73, 84, 67] the target: 72
when input is [76, 69, 2, 66, 73, 84, 67, 72] the target: 2
when input is [78] the target: 79
when input is [78, 79] the target: 84
when input is [78, 79, 84] the target: 2
when input is [78, 79, 84, 2] the target: 68
when input is [78, 79, 84, 2, 68] the target: 85
when input is [78, 

In [21]:
print(xb) # our input to the transformer

tensor([[76, 69,  2, 66, 73, 84, 67, 72],
        [78, 79, 84,  2, 68, 85, 77, 66],
        [78, 68,  2, 71, 69, 84, 65, 87],
        [69,  2, 87, 72, 79,  2, 79, 66]])


In [22]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 95])
tensor(5.0575, grad_fn=<NllLossBackward0>)
?Z4/4=[=(+2a9
*p-y\ei'] 7[YFG!dL"Ikm4
R f[R3l|wwq4K3PNh$LqM{nA&b^/`bFa#pxppn!I%1d{l+j{*Wi7"fAD-9LF0


In [23]:


# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)



In [24]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


5.040060520172119


In [25]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))

jbWlh
+naoQj[/zOca["#0ece:VvmD;XJ
O$xmghe8HSJD'xaX(J@kPPSpGUDilohAO):;~2QlS[ ,eTfO|GX
[=jm4t^h*E@x*3RhgBp,TFFnbf[t]x#z7.twj3PvnUrBay~Q-OkbjU1TzDheAsJOE/3k}4K/&c{$7@y/.sM41Vz=EYQ=?C:lo#l'fu
,,rTFg)R?s7&O$nEHSrPl ?Nv0}q;v`!,xvC}+\$L=}4deOEN?%y~Br
"{^_u8v:{aXt.BnF[AC:rPjuA&o#'qd7^r|pID1",xo)^XBa+?B*]cBakfeTSs(sbktX
1
Bsb=#YubC:Z\97N]zhR LSHTeT9)+DHR3g'wlibi8cD=\@-W?M4!C#|'?S'Y^QUrB5[tY=(+4@'jIPIFc7NY|@49Cf\W7Q+#]a+hh3dARZ?1%eDh:l3V(il 
,A/#YX%wgZse9w.^
dA=a&h
c=I@HPn-R|0'/yX( SfAqO`2/+s
Z!h)p


In [26]:


# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)



a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [27]:
torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [28]:


# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)



In [29]:


# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)



True

In [30]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)

True

In [31]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [32]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

In [33]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5



In [34]:
k.var()

tensor(1.0449)

In [35]:
q.var()

tensor(1.0700)

In [36]:
wei.var()

tensor(1.0918)

In [37]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [38]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [39]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape


torch.Size([32, 100])

In [40]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs


(tensor(0.1469), tensor(0.8803))

In [41]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [42]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 50000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open(txt_path, 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))

0.213599 M parameters
step 0: train loss 4.7641, val loss 4.7646
step 100: train loss 2.7636, val loss 2.7415
step 200: train loss 2.6236, val loss 2.5927
step 300: train loss 2.5275, val loss 2.5192
step 400: train loss 2.4772, val loss 2.4576
step 500: train loss 2.4345, val loss 2.3969
step 600: train loss 2.3858, val loss 2.3683
step 700: train loss 2.3246, val loss 2.2971
step 800: train loss 2.2696, val loss 2.2501
step 900: train loss 2.2363, val loss 2.2089
step 1000: train loss 2.2080, val loss 2.1901
step 1100: train loss 2.1804, val loss 2.1382
step 1200: train loss 2.1525, val loss 2.1091
step 1300: train loss 2.1250, val loss 2.1028
step 1400: train loss 2.0868, val loss 2.0606
step 1500: train loss 2.0790, val loss 2.0432
step 1600: train loss 2.0628, val loss 2.0424
step 1700: train loss 2.0451, val loss 2.0165
step 1800: train loss 2.0288, val loss 1.9854
step 1900: train loss 2.0276, val loss 1.9780
step 2000: train loss 2.0099, val loss 1.9648
step 2100: train loss 1.